services:
  postgres:
    image: postgres:15-alpine
    container_name: gpt_chat_bot_db
    environment:
      POSTGRES_DB: gpt_chat_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
