// <auto-generated />
using System;
using DataBaseLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseLayer.Migrations.Sqlite
{
    [DbContext(typeof(StoreContext))]
    partial class SqliteStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DataBaseLayer.Models.AIBilingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramChatInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TelegramChatInfoId");

                    b.HasIndex("TelegramUserInfoId");

                    b.ToTable("AIBilingItem");
                });

            modelBuilder.Entity("DataBaseLayer.Models.BalanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModifiedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BalanceHistories");
                });

            modelBuilder.Entity("DataBaseLayer.Models.CachedTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedTranslations");
                });

            modelBuilder.Entity("DataBaseLayer.Models.HistoryMessage", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DataBaseLayer.Models.TelegramChatInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteLink")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TelegramChatInfos");
                });

            modelBuilder.Entity("DataBaseLayer.Models.TelegramUserInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BalanceModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAiInteraction")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TelegramUserInfos");
                });

            modelBuilder.Entity("DataBaseLayer.Models.AIBilingItem", b =>
                {
                    b.HasOne("DataBaseLayer.Models.TelegramChatInfo", "TelegramChatInfo")
                        .WithMany()
                        .HasForeignKey("TelegramChatInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBaseLayer.Models.TelegramUserInfo", "TelegramUserInfo")
                        .WithMany()
                        .HasForeignKey("TelegramUserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramChatInfo");

                    b.Navigation("TelegramUserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
