// This partial declaration makes the top-level Program class accessible from
// test projects using WebApplicationFactory<Program>.
// It is generated by the C# compiler for top-level statements, but needs to
// be explicitly re-exported as 'public' for test assemblies.

// ReSharper disable once CheckNamespace
public partial class Program { }
